### ISSUE TITLE
Keine Adaptereinstellungen / 404 Page you're looking for can't be found 

### ISSUE THREAD

**Issue by mac89muc** [ioBroker/ioBroker.matter#10]
Hallo zusammen,

Adapter ist ja noch nicht final und nur über Git zu installieren - aus Neugier um irgendwann mal meine Eve Thermos (wenn das Matter Update da ist) zu integrieren habe ich mir den Adapter mal installiert.

Installation läuft soweit durch - allerdings kann ich den Adapter nicht konfigurieren, da die Fehlermeldung auf dem Bild erscheint.

![image](https://github.com/ioBroker/ioBroker.matter/assets/69312437/9aae3acc-f6a9-4965-aa31-f12fcec46740)

Gruß

macOS Installation 14.2 Sonoma auf Mac mini m2 
node.js 18.18.2
NPM 9.8.1
js-controller 5.0.17

**Comment by chrispi68** [comment]
Ich habe das gleiche Problem und den Adapter wieder deinstalliert.

**Comment by Apollon77** [comment]
Naja, Ihr seid viel zu früh ... einen noch nirgends angekündigten Adapter einfach mal so zu installieren birg gefahren. Bitte einfach abwarten bis wir den Adapter offiziell ankündigen

**Comment by chrispi68** [comment]
Alles klar, danke für die Info. Bei Bedarf kann ich gerne den Test unterstützen.

**Comment by Apollon77** [comment]
ich lasse hier offen und melden uns dann hier und auch im Forum

**Comment by CommanderXXL** [comment]
Ich wollte mal fragen ob hier in naher Zukunft noch was passiert? Ist jetzt seit fast einem halben Jahr nichts neues mehr passiert. Ich hoffe das Projekt "Matter" ist nicht tot?

**Comment by Apollon77** [comment]
Nein es wird aktiv daran gearbeitet. Kommt sobald es fertig ist

**Comment by CommanderXXL** [comment]
Oh cool. Freut mich sehr zu hören und danke für das superschnelle Feedback. Ich bin gerne Betatester sobald es was neues gibt.

**Comment by Apollon77** [comment]
It comes when it comes :-) Not too long
