### ISSUE TITLE
Change Devices/Bridges: Always allow to pair via QR-Code

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.matter#138]
The current logic is that we show a QR Code icon if the device is NOT commissioned yet and else the connect symbol with the list of connected controllers.

In fact we can also open a "Local commissioning window" anytime, so then people can scan in adapter UI for a second Ecosystem and do not need to get the code from it. For this we need to adjust the logic in UI a bit:
* Always show QR code and when clicking we send a backend call which returns the QR code data. Command could be "controllerAllowCommissioning" ... i then implement backend side
* When commissioned then show connection symbol, else not.

**Comment by Feuer-sturm** [comment]
matter 0.3.2
is fixed
![grafik](https://github.com/user-attachments/assets/18fdb591-63f9-46dc-9b71-d42a59fe9f78)
