### ISSUE TITLE
Remove productid/vendorid from bridged devices

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.matter#167]
When the add devices dialog is used to add devices for a bridge please remove the productid/Vendor id column. This one makes only (a bit) sense when adding separate devices,

But also there we could hide these columns between a "specify device specific product/vendor ids" setting for the dialog

<img width="668" alt="Bildschirmfoto 2024-11-27 um 21 52 03" src="https://github.com/user-attachments/assets/6665fc17-5d1e-4895-bfbd-cc1965cb95ee">

**Comment by Apollon77** [comment]
Fixed in 0.2.3

**Comment by Feuer-sturm** [comment]
is fixed with 0.2.3
