### ISSUE TITLE
Fehlerhafte Darstellung im Fenster "Hinweise zur Inbetriebnahme" wenn ein Gerät hinzugefügt wird

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.matter#170]
Nachdem ein Gerät neu hinzugefügt wurde, werden im folgenden Fenster zwei Einträge angezeigt:

![grafik](https://github.com/user-attachments/assets/a4920783-b8a8-479a-8499-3a8fdcc833f3)

Wenn man das Gerät einmal neu startet, dann wird im Fenster "Hinweise zur Inbetriebnahme" nur ein Eintrag korrekterweise aufgeführt

**Comment by Feuer-sturm** [comment]
matter 0.2.2

das Popup erscheint gar nicht mehr, nachdem das Gerät verknüpft wurde @Apollon77 -> ist das so gewollt?
Wenn man auf das grüne Wlan Symbol klickt wird jetzt korrekterweise nur noch eine grüne Verbindung angezeigt -> i.O.

**Comment by Apollon77** [comment]
Mir wäre neu das das Popup automatisch kommt ... das wäre dann eher ein (anderer) bug. Aber das nur ein Eintrag da ist ist korrekt

**Comment by Feuer-sturm** [comment]
@Apollon77 bei der 0 2.1 wurde das popup mach der Einrichtung angezeigt, daher die Frage. Wenn es sich nicht automatisch öffnen soll dann ist es "works as designed"

**Comment by Apollon77** [comment]
@Feuer-sturm Daran habe ich nichts geändert ... also wenn es so angezeigt wurd e dann sollte das weiter passierren. Alle Änderungen die ich egtan habe waren im backend. Also wenn wäre das eine Frage für Denis :-)

**Comment by Feuer-sturm** [comment]
mit der 0.2.3 war das popup jetzt da.
Sieht also erstmal gut aus :)
