### ISSUE TITLE
Gerät mit Temp + Humidity - Temp Wert nicht korrekt, Humidity wird nicht exposed

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.matter#178]
matter 0.2.3

- In Admin ein Device mit Temperatur + Luftfeuchtigkeit angelegt, welches sich die Werte von einem HMIP Sensor Temp + Luftfeuchtigkeit holt
- Dieses Device in matter.0 als eigenes Gerät anlegen

**Problem 1**
Im Log wurde das Gerät nochmal neu eingerichtet und mit Google Home verbunden
In der Kachel wird nur die Temperatur angezeigt
Im Datenpunkt für die Temperatur vom alias alias.0.DevicesMatter.HMIPTemp_Luftfeuchtigkeit.ACTUAL stehen 21,7° in der App werden 21,5 angezeigt

**Problem 2**
humidity wird nicht exposed

Logfile
[log.txt](https://github.com/user-attachments/files/17965172/log.txt)

**Comment by Feuer-sturm** [comment]
Problem 1 - gelöst
In Google werden die Werte gerundet, in Apple werden sie genau dargestellt. Kein Bug im Adapter.

**Comment by Apollon77** [comment]
My assumption is that you have set the "no compose" option on this device. could this be? In this case for a normal device only the first endpoint gets added. Please retest with next version

**Comment by Apollon77** [comment]
Please recheck with 0.2.4 - and make sure to NOT tick "no compose" setting! if you have it then it is now logged

**Comment by Feuer-sturm** [comment]
matter 0.2.4
@Apollon77 

- Create new device and setting "no compose" (Keine zusammengesetzten Geräte) NOT activated
- Device linked with google home -> ok
- Only temperature and no humidity is shown in the app -> not ok
- Open settings in iobroker of the device and the option "no compose" is now automatically activated -> not ok

Log
[log1.txt](https://github.com/user-attachments/files/18021891/log1.txt)

**Comment by Feuer-sturm** [comment]
2nd Test
- Reset device to factory settings and deleted it in google home app
- manually changed object matter.0.devices.7fc45b99-272c-4917-8b86-eff7502dc62d value     "noComposed" to the value false
- link device once again with google home
- Now Temperature AND humidity is shown in the app

**Comment by Feuer-sturm** [comment]
v0.2.5

its working and both values are shown in google home app :)
