### ISSUE TITLE
Alle Bridges haben in Google Home App den gleichen Namen

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.matter#179]
Wenn man mehrere ioBroker Bridges anlegt und diese in Google Home hinzufügt, dann kann man für diese Bridges keinen Namen vergeben, die heißen immer "ioBrokder Bridge". Kann man das ändern, das hier der Name der Bridge aus ioBroker übertragen wird?

**Comment by Apollon77** [comment]
please check 0.2.4

**Comment by Feuer-sturm** [comment]
is fixed with 0.2.5 :)
