### ISSUE TITLE
Expose Device/Bridge infos from Backend in UI

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.matter#181]
After creating a device or a device in a bridge we should expose some informations to support the user to understand what is mapped how and such

So my idea is the following:
* In "Devices" and for a bridge and for a bridged device we should add an "info icon" which sends a "getdetails" command to the backend
* Backend returns a JSONConfig return with panel/tabs and such
* UI shows the content in a overlay dialog and allows to close the details

**Comment by GermanBluefox** [comment]
GUI implemented

**Comment by Apollon77** [comment]
Ifo Button shows some details already - especially the mapped states of the device. To be enhanced

**Comment by Feuer-sturm** [comment]
matter 0.3.2
This is already implemented
![grafik](https://github.com/user-attachments/assets/2427d915-03b4-4d1f-a43d-f368c6a18898)


@Apollon77 Which information shall be added?

**Comment by Apollon77** [comment]
In fact as shown in discord the Bridge AND each bridged device have such an "Info" button once initialized in backend (s o might take some seconds to appear). For devices only the device has it

**Comment by Feuer-sturm** [comment]
@Apollon77 Thanks for explenation.
Shall this issue stay open?
You wrote some comments above "To be enhanced", because of this I wanted to know (document here in the issue) which additional information should be shown to the user. If additional information will add during devlopment to the popups we can close the issue.

**Comment by Apollon77** [comment]
We will enhance over time. I will close here
