### ISSUE TITLE
No UI / Config in Instances using 0.2.3

### ISSUE THREAD

**Issue by kesch001de** [ioBroker/ioBroker.matter#186]
System:
Description: Ubuntu 24.04.1 LTS
Release: 24.04
Codename: noble
js-controller: 7.0.3
node: 20.18.1

Hi guys, 

Installing 0.2.3, no UI is shown in Instances.
Entry "matter" in Objects is available - but no further objects.
Entry in Adapter is available.

Installation log:
$ iobroker url ioBroker/ioBroker.matter --host HOMESERVER --debug
install ioBroker/ioBroker.matter
Installing ioBroker/ioBroker.matter... (System call)
npm warn deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supportednpm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated gauge@4.0.4: This package is no longer supported.
> @stoprocent/bleno@0.8.1 install> node-gyp-build
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.1gyp info using node@20.18.1 | linux | x64
gyp info find Python using Python version 3.12.3 found at "/usr/bin/python3"
gyp info spawn args [gyp info spawn args '/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py',gyp info spawn args 'binding.gyp',gyp info spawn args '-f',gyp info spawn args 'make',gyp info spawn args '-I',
gyp info spawn args '--depth=.',gyp info spawn args '--no-parallel',gyp info spawn args '--generator-output',gyp info spawn args 'build',gyp info spawn args '-Goutput_dir=.'gyp info spawn args ]
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Verzeichnis „/opt/iobroker/node_modules/@stoprocent/bleno/build“ wird betreten
SOLINK_MODULE(target) Release/obj.target/bleno.node
COPY Release/bleno.node
gyp info ok
> @stoprocent/bluetooth-hci-socket@1.4.1 install> node-gyp-build
> @stoprocent/noble@1.15.1 install> node-gyp-build
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.1
gyp info using node@20.18.1 | linux | x64
gyp info find Python using Python version 3.12.3 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args '-Dnode_engine=v8',gyp info spawn args '--depth=.',gyp info spawn args '--no-parallel',gyp info spawn args '--generator-output',gyp info spawn args 'build',gyp info spawn args '-Goutput_dir=.'gyp info spawn args ]
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Verzeichnis „/opt/iobroker/node_modules/@stoprocent/noble/build“ wird betreten
SOLINK_MODULE(target) Release/obj.target/noble.node
COPY Release/noble.node
make: Verzeichnis „/opt/iobroker/node_modules/@stoprocent/noble/build“ wird verlassen
gyp info ok
> usb@2.14.0 install> node-gyp-build
207 packages are looking for funding run `npm fund` for details
upload [0] matter.admin /opt/iobroker/node_modules/iobroker.matter/admin/matter.png matter.png image/png
Updating objects from io-package.json for adapter "matter" with version "0.2.3"
Process exited with code 0

No further entries in Protokoll.

Did i miss something else to get the UI as well?

Thanks a lot!

**Comment by Feuer-sturm** [comment]
@kesch001de How did you install matter Adapter? Here you find the description for the installation: https://github.com/ioBroker/ioBroker.matter/wiki#installation

To configure matter go to instances -> matter.0 -> select the screwdriver

**Comment by kesch001de** [comment]
hi @Feuer-sturm 
i did it with option A using "Katze" but w/o adding the exact version.
re-installation did not change anything as well.

exactly this option / entry is not given as its usually there for all other adapter.
To configure matter go to instances -> matter.0 -> select the screwdriver

thx!

**Comment by Feuer-sturm** [comment]
@kesch001de Please delete the adpater completely and install it from scratch wich this command in the ui:
`iobroker.matter@0.2.3`

**Comment by Feuer-sturm** [comment]
@kesch001de If you want to participate to the alpha test https://forum.iobroker.net/topic/78133/matter-adapter-tester-f%C3%BCr-alpha-phase-gesucht please contact @Apollon77 . He can give you access to the discord server where we are talking about the results of the alpha test of the matter adapter

**Comment by kesch001de** [comment]
@Feuer-sturm adding the version, the log looks different now:

$ iobroker url https://github.com/ioBroker/iobroker.matter@0.2.3 --host HOMESERVER --debug
install ioBroker/iobroker.matter@0.2.3
NPM version: 10.8.2
Installing ioBroker/iobroker.matter@0.2.3... (System call)
npm error code ENOENT
npm error errno -2npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/opt/iobroker/ioBroker/iobroker.matter@0.2.3/package.json'npm error enoent This is related to npm not being able to find a file.npm error enoent
npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-12-01T11_42_08_126Z-debug-0.log
npm error code ENOENTnpm error syscall opennpm error path /opt/iobroker/ioBroker/iobroker.matter@0.2.3/package.jsonnpm error errno -2npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/opt/iobroker/ioBroker/iobroker.matter@0.2.3/package.json'npm error enoent This is related to npm not being able to find a file.npm error enoentnpm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-12-01T11_42_08_126Z-debug-0.log
host.HOMESERVER Cannot install ioBroker/iobroker.matter@0.2.3: 254
ERROR: Process exited with code 25

cat /home/iobroker/.npm/_logs/2024-12-01T11_42_08_126Z-debug-0.log
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.8.2
2 info using node@v20.18.1
3 silly config load:file:/usr/lib/node_modules/npm/npmrc
4 silly config load:file:/opt/iobroker/.npmrc
5 silly config load:file:/home/iobroker/.npmrc
6 silly config load:file:/usr/etc/npmrc
7 verbose title npm install ioBroker/iobroker.matter@0.2.3
8 verbose argv "install" "--save-exact" "ioBroker/iobroker.matter@0.2.3" "--foreground-scripts"
9 verbose logfile logs-max:10 dir:/home/iobroker/.npm/_logs/2024-12-01T11_42_08_126Z-
10 verbose logfile /home/iobroker/.npm/_logs/2024-12-01T11_42_08_126Z-debug-0.log
11 silly packumentCache heap:2197815296 maxSize:549453824 maxEntrySize:274726912
12 silly logfile start cleaning logs, removing 1 files
13 silly logfile done cleaning log files
14 verbose stack Error: Could not read package.json: Error: ENOENT: no such file or directory, open '/opt/iobroker/ioBroker/iobroker.matter@0.2.3/package.js                                                 on'
14 verbose stack     at async open (node:internal/fs/promises:639:25)
14 verbose stack     at async readFile (node:internal/fs/promises:1242:14)
14 verbose stack     at async read (/usr/lib/node_modules/npm/node_modules/@npmcli/package-json/lib/read-package.js:9:18)
14 verbose stack     at async PackageJson.load (/usr/lib/node_modules/npm/node_modules/@npmcli/package-json/lib/index.js:130:31)
14 verbose stack     at async PackageJson.normalize (/usr/lib/node_modules/npm/node_modules/@npmcli/package-json/lib/index.js:116:5)
14 verbose stack     at async /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:512:22
14 verbose stack     at async Promise.all (index 0)
14 verbose stack     at async #add (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:501:5)
14 verbose stack     at async #applyUserRequestsToNode (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:470:7)
14 verbose stack     at async #applyUserRequests (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:405:7)
15 error code ENOENT
16 error syscall open
17 error path /opt/iobroker/ioBroker/iobroker.matter@0.2.3/package.json
18 error errno -2
19 error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/opt/iobroker/ioBroker/iobroker.matter@0.2.3/package.json'
20 error enoent This is related to npm not being able to find a file.
20 error enoent
21 silly unfinished npm timer reify 1733053328534
22 silly unfinished npm timer reify:loadTrees 1733053328548
23 silly unfinished npm timer idealTree:userRequests 1733053329607
24 verbose cwd /opt/iobroker
25 verbose os Linux 6.8.0-49-generic
26 verbose node v20.18.1
27 verbose npm  v10.8.2
28 verbose exit -2
29 verbose code -2
30 error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-12-01T11_42_08_126Z-debug-0.log

**Comment by Feuer-sturm** [comment]
@kesch001de did you use the command I wrote?
iobroker.matter@0.2.3

![grafik](https://github.com/user-attachments/assets/99c0247d-8ab2-46ef-807e-7ba74965ff06)


my log:
`$ iobroker url iobroker.matter@0.2.3 --host ioB-Prod-Testsystem --debug`


your log:
`$ iobroker url https://github.com/ioBroker/iobroker.matter@0.2.3 --host HOMESERVER --debug`

**Comment by kesch001de** [comment]
@Feuer-sturm all good now
adapter is up and running

thx for the support - much appreciated!
