### ISSUE TITLE
adding alias objects / objects with long names, adapter will crash

### ISSUE THREAD

**Issue by kesch001de** [ioBroker/ioBroker.matter#188]
hi all, 

adding a device out of an alias, the adapter will crash and loops on restarting.

<html>
<body>

matter.0 | 2024-12-01 19:54:07.713 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
matter.0 | 2024-12-01 19:54:07.712 | info | terminating
matter.0 | 2024-12-01 19:54:07.699 | error | 9d209b29-7f7d-4e3d-8350-c0bec0dbe945 is not initialized
matter.0 | 2024-12-01 19:54:07.698 | error | Error: 9d209b29-7f7d-4e3d-8350-c0bec0dbe945 is not initialized at Object.assertActive (/opt/iobroker/node_modules/@matter/general/src/util/Lifecycle.ts:42:23) at AsyncConstruction.assert (/opt/iobroker/node_modules/@matter/general/src/util/Construction.ts:284:23) at Endpoint.act (/opt/iobroker/node_modules/@matter/node/src/endpoint/Endpoint.ts:552:27) at Endpoint.set (/opt/iobroker/node_modules/@matter/node/src/endpoint/Endpoint.ts:174:20) at HumidityToMatter.registerIoBrokerHandlersAndInitialize (/opt/iobroker/node_modules/iobroker.matter/src/matter/to-matter/HumidityToMatter.ts:54:36) at HumidityToMatter.init (/opt/iobroker/node_modules/iobroker.matter/src/matter/to-matter/GenericDeviceToMatter.ts:92:20) at BridgedDevices.addBridgedIoBrokerDevice (/opt/iobroker/node_modules/iobroker.matter/src/matter/BridgedDevicesNode.ts:103:33) at processTicksAndRejections (node:internal/process/task_queues:95:5) at BridgedDevices.init (/opt/iobroker/node_modules/iobroker.matter/src/matter/BridgedDevicesNode.ts:174:13) at MatterAdapter.createMatterBridge (/opt/iobroker/node_modules/iobroker.matter/src/main.ts:829:13)
matter.0 | 2024-12-01 19:54:07.667 | error | unhandled promise rejection: 9d209b29-7f7d-4e3d-8350-c0bec0dbe945 is not initialized
matter.0 | 2024-12-01 19:54:07.667 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
matter.0 | 2024-12-01 19:54:07.665 | error | Error adding endpoint 9d209b29-7f7d-4e3d-8350-c0bec0dbe945 to bridge: Behaviors have errors at /opt/iobroker/node_modules/@matter/node/src/endpoint/properties/Behaviors.ts:171:27 at all (/opt/iobroker/node_modules/@matter/general/src/util/Construction.ts:699:25) at /opt/iobroker/node_modules/@matter/general/src/util/Construction.ts:689:17 at processTicksAndRejections (node:internal/process/task_queues:95:5) Cause #0: Error initializing db18c7b1-f7fe-4a16-9aea-50ad553606a3.bridge.9d209b29-7f7d-4e3d-8350-c0bec0dbe945.bridgedDeviceBasicInformation at crash (/opt/iobroker/node_modules/@matter/node/src/behavior/internal/BehaviorBacking.ts:66:19) at processTicksAndRejections (node:internal/process/task_queues:95:5) Caused by: Validating db18c7b1-f7fe-4a16-9aea-50ad553606a3.bridge.9d209b29-7f7d-4e3d-8350-c0bec0dbe945.bridgedDeviceBasicInformation.state.productName: Constraint "all": Lenght of value AK Raumthermostat HumidityLevel humidity is not within bounds defined by constraint (135) at /opt/iobroker/node_modules/@matter/node/src/behavior/state/validation/constraint.ts:70:27 at /opt/iobroker/node_modules/@matter/node/src/behavior/state/validation/ValueValidator.ts:209:9 at Object.productName (/opt/iobroker/node_modules/@matter/node/src/behavior/state/validation/conformance.ts:32:13) at validateStruct (/opt/iobroker/node_modules/@matter/node/src/behavior/state/validation/ValueValidator.ts:251:28) at Object.validate (/opt/iobroker/node_modules/@matter/node/src/behavior/state/managed/Datasource.ts:92:13) at finalizeState (/opt/iobroker/node_modules/@matter/node/src/behavior/internal/ServerBehaviorBacking.ts:37:29) at processTicksAndRejections (node:internal/process/task_queues:95:5)
matter.0 | 2024-12-01 19:54:07.621 | warn | 2024-12-01 19:54:07.621 ERROR Transaction Rolling back initialize<db18c7b1-f7fe-4a16-9aea-50ad553606a3.bridge.9d209b29-7f7d-4e3d-8350-c0bec0dbe945>#17 due to error: Behaviors have errors
matter.0 | 2024-12-01 19:54:07.367 | info | 2024-12-01 19:54:07.367 WARN BasicInformationServer Using development values for some BasicInformation attributes: hardwareVersion: 0 softwareVersion: 0
matter.0 | 2024-12-01 19:54:07.194 | error | Type detection mismatch for state 0_userdata.0.Matter.Devices.MatterTemp1: thermostat !== temperature. Initialize device with just this one state.
matter.0 | 2024-12-01 19:54:07.155 | error | Type detection mismatch for state 0_userdata.0.Matter.Devices.MatterHum1: info !== humidity. Initialize device with just this one state.
matter.0 | 2024-12-01 19:54:07.061 | error | Type detection mismatch for state alias.0.BoschSmartHome.AKZ Luftfeuchtigkeit: thermostat !== humidity. Initialize device with just this one state.
matter.0 | 2024-12-01 19:54:06.868 | error | Can not read version from package.json: Error: Cannot find module './package.json' Require stack: - /opt/iobroker/node_modules/iobroker.matter/build/main.js
matter.0 | 2024-12-01 19:54:06.848 | info | starting. Version 0.2.3 in /opt/iobroker/node_modules/iobroker.matter, node: v20.18.1, js-controller: 7.0.3
host.HOMESERVER | 2024-12-01 19:53:32.422 | error | instance system.adapter.matter.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.HOMESERVER | 2024-12-01 19:53:32.422 | error | Caught by controller[1]: at MatterAdapter.createMatterBridge (/opt/iobroker/node_modules/iobroker.matter/src/main.ts:829:13)
host.HOMESERVER | 2024-12-01 19:53:32.422 | error | Caught by controller[1]: at BridgedDevices.init (/opt/iobroker/node_modules/iobroker.matter/src/matter/BridgedDevicesNode.ts:174:13)
host.HOMESERVER | 2024-12-01 19:53:32.422 | error | Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.HOMESERVER | 2024-12-01 19:53:32.422 | error | Caught by controller[1]: at BridgedDevices.addBridgedIoBrokerDevice (/opt/iobroker/node_modules/iobroker.matter/src/matter/BridgedDevicesNode.ts:103:33)
host.HOMESERVER | 2024-12-01 19:53:32.422 | error | Caught by controller[1]: at HumidityToMatter.init (/opt/iobroker/node_modules/iobroker.matter/src/matter/to-matter/GenericDeviceToMatter.ts:92:20)
host.HOMESERVER | 2024-12-01 19:53:32.422 | error | Caught by controller[1]: at HumidityToMatter.registerIoBrokerHandlersAndInitialize (/opt/iobroker/node_modules/iobroker.matter/src/matter/to-matter/HumidityToMatter.ts:54:36)
host.HOMESERVER | 2024-12-01 19:53:32.422 | error | Caught by controller[1]: at Endpoint.set (/opt/iobroker/node_modules/@matter/node/src/endpoint/Endpoint.ts:174:20)
host.HOMESERVER | 2024-12-01 19:53:32.422 | error | Caught by controller[1]: at Endpoint.act (/opt/iobroker/node_modules/@matter/node/src/endpoint/Endpoint.ts:552:27)
host.HOMESERVER | 2024-12-01 19:53:32.422 | error | Caught by controller[1]: at AsyncConstruction.assert (/opt/iobroker/node_modules/@matter/general/src/util/Construction.ts:284:23)
host.HOMESERVER | 2024-12-01 19:53:32.422 | error | Caught by controller[1]: at Object.assertActive (/opt/iobroker/node_modules/@matter/general/src/util/Lifecycle.ts:42:23)
host.HOMESERVER | 2024-12-01 19:53:32.422 | error | Caught by controller[1]: Error: 9d209b29-7f7d-4e3d-8350-c0bec0dbe945 is not initialized
host.HOMESERVER | 2024-12-01 19:53:32.421 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
matter.0 | 2024-12-01 19:53:31.743 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
matter.0 | 2024-12-01 19:53:31.742 | info | terminating
matter.0 | 2024-12-01 19:53:31.728 | error | 9d209b29-7f7d-4e3d-8350-c0bec0dbe945 is not initialized
matter.0 | 2024-12-01 19:53:31.727 | error | Error: 9d209b29-7f7d-4e3d-8350-c0bec0dbe945 is not initialized at Object.assertActive (/opt/iobroker/node_modules/@matter/general/src/util/Lifecycle.ts:42:23) at AsyncConstruction.assert (/opt/iobroker/node_modules/@matter/general/src/util/Construction.ts:284:23) at Endpoint.act (/opt/iobroker/node_modules/@matter/node/src/endpoint/Endpoint.ts:552:27) at Endpoint.set (/opt/iobroker/node_modules/@matter/node/src/endpoint/Endpoint.ts:174:20) at HumidityToMatter.registerIoBrokerHandlersAndInitialize (/opt/iobroker/node_modules/iobroker.matter/src/matter/to-matter/HumidityToMatter.ts:54:36) at HumidityToMatter.init (/opt/iobroker/node_modules/iobroker.matter/src/matter/to-matter/GenericDeviceToMatter.ts:92:20) at BridgedDevices.addBridgedIoBrokerDevice (/opt/iobroker/node_modules/iobroker.matter/src/matter/BridgedDevicesNode.ts:103:33) at processTicksAndRejections (node:internal/process/task_queues:95:5) at BridgedDevices.init (/opt/iobroker/node_modules/iobroker.matter/src/matter/BridgedDevicesNode.ts:174:13) at MatterAdapter.createMatterBridge (/opt/iobroker/node_modules/iobroker.matter/src/main.ts:829:13)
matter.0 | 2024-12-01 19:53:31.697 | error | unhandled promise rejection: 9d209b29-7f7d-4e3d-8350-c0bec0dbe945 is not initialized
matter.0 | 2024-12-01 19:53:31.697 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
matter.0 | 2024-12-01 19:53:31.695 | error | Error adding endpoint 9d209b29-7f7d-4e3d-8350-c0bec0dbe945 to bridge: Behaviors have errors at /opt/iobroker/node_modules/@matter/node/src/endpoint/properties/Behaviors.ts:171:27 at all (/opt/iobroker/node_modules/@matter/general/src/util/Construction.ts:699:25) at /opt/iobroker/node_modules/@matter/general/src/util/Construction.ts:689:17 at processTicksAndRejections (node:internal/process/task_queues:95:5) Cause #0: Error initializing db18c7b1-f7fe-4a16-9aea-50ad553606a3.bridge.9d209b29-7f7d-4e3d-8350-c0bec0dbe945.bridgedDeviceBasicInformation at crash (/opt/iobroker/node_modules/@matter/node/src/behavior/internal/BehaviorBacking.ts:66:19) at processTicksAndRejections (node:internal/process/task_queues:95:5) Caused by: Validating db18c7b1-f7fe-4a16-9aea-50ad553606a3.bridge.9d209b29-7f7d-4e3d-8350-c0bec0dbe945.bridgedDeviceBasicInformation.state.productName: Constraint "all": Lenght of value AK Raumthermostat HumidityLevel humidity is not within bounds defined by constraint (135) at /opt/iobroker/node_modules/@matter/node/src/behavior/state/validation/constraint.ts:70:27 at /opt/iobroker/node_modules/@matter/node/src/behavior/state/validation/ValueValidator.ts:209:9 at Object.productName (/opt/iobroker/node_modules/@matter/node/src/behavior/state/validation/conformance.ts:32:13) at validateStruct (/opt/iobroker/node_modules/@matter/node/src/behavior/state/validation/ValueValidator.ts:251:28) at Object.validate (/opt/iobroker/node_modules/@matter/node/src/behavior/state/managed/Datasource.ts:92:13) at finalizeState (/opt/iobroker/node_modules/@matter/node/src/behavior/internal/ServerBehaviorBacking.ts:37:29) at processTicksAndRejections (node:internal/process/task_queues:95:5)
matter.0 | 2024-12-01 19:53:31.651 | warn | 2024-12-01 19:53:31.651 ERROR Transaction Rolling back initialize<db18c7b1-f7fe-4a16-9aea-50ad553606a3.bridge.9d209b29-7f7d-4e3d-8350-c0bec0dbe945>#17 due to error: Behaviors have errors
matter.0 | 2024-12-01 19:53:31.399 | info | 2024-12-01 19:53:31.399 WARN BasicInformationServer Using development values for some BasicInformation attributes: hardwareVersion: 0 softwareVersion: 0
matter.0 | 2024-12-01 19:53:31.219 | error | Type detection mismatch for state 0_userdata.0.Matter.Devices.MatterTemp1: thermostat !== temperature. Initialize device with just this one state.
matter.0 | 2024-12-01 19:53:31.179 | error | Type detection mismatch for state 0_userdata.0.Matter.Devices.MatterHum1: info !== humidity. Initialize device with just this one state.
matter.0 | 2024-12-01 19:53:31.073 | error | Type detection mismatch for state alias.0.BoschSmartHome.AKZ Luftfeuchtigkeit: thermostat !== humidity. Initialize device with just this one state.
matter.0 | 2024-12-01 19:53:30.879 | error | Can not read version from package.json: Error: Cannot find module './package.json' Require stack: - /opt/iobroker/node_modules/iobroker.matter/build/main.js
matter.0 | 2024-12-01 19:53:30.859 | info | starting. Version 0.2.3 in /opt/iobroker/node_modules/iobroker.matter, node: v20.18.1, js-controller: 7.0.3
admin.0 | 2024-12-01 19:52:57.589 | info | <== Disconnect system.user.admin from ::ffff:192.168.1.116 matter
admin.0 | 2024-12-01 19:52:57.589 | info | <== Disconnect system.user.admin from ::ffff:192.168.1.116 matter
host.HOMESERVER | 2024-12-01 19:52:56.448 | error | instance system.adapter.matter.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.HOMESERVER | 2024-12-01 19:52:56.448 | error | Caught by controller[1]: at MatterAdapter.onObjectChange (/opt/iobroker/node_modules/iobroker.matter/src/main.ts:543:13)
host.HOMESERVER | 2024-12-01 19:52:56.448 | error | Caught by controller[1]: at MatterAdapter.syncDevices (/opt/iobroker/node_modules/iobroker.matter/src/main.ts:1016:21)
host.HOMESERVER | 2024-12-01 19:52:56.448 | error | Caught by controller[1]: at BridgedDevices.applyConfiguration (/opt/iobroker/node_modules/iobroker.matter/src/matter/BridgedDevicesNode.ts:211:17)
host.HOMESERVER | 2024-12-01 19:52:56.448 | error | Caught by controller[1]: at BridgedDevices.addBridgedIoBrokerDevice (/opt/iobroker/node_modules/iobroker.matter/src/matter/BridgedDevicesNode.ts:103:33)
host.HOMESERVER | 2024-12-01 19:52:56.448 | error | Caught by controller[1]: at HumidityToMatter.init (/opt/iobroker/node_modules/iobroker.matter/src/matter/to-matter/GenericDeviceToMatter.ts:92:20)
host.HOMESERVER | 2024-12-01 19:52:56.448 | error | Caught by controller[1]: at HumidityToMatter.registerIoBrokerHandlersAndInitialize (/opt/iobroker/node_modules/iobroker.matter/src/matter/to-matter/HumidityToMatter.ts:54:36)
host.HOMESERVER | 2024-12-01 19:52:56.447 | error | Caught by controller[1]: at Endpoint.set (/opt/iobroker/node_modules/@matter/node/src/endpoint/Endpoint.ts:174:20)
host.HOMESERVER | 2024-12-01 19:52:56.447 | error | Caught by controller[1]: at Endpoint.act (/opt/iobroker/node_modules/@matter/node/src/endpoint/Endpoint.ts:552:27)
host.HOMESERVER | 2024-12-01 19:52:56.447 | error | Caught by controller[1]: at AsyncConstruction.assert (/opt/iobroker/node_modules/@matter/general/src/util/Construction.ts:284:23)
host.HOMESERVER | 2024-12-01 19:52:56.447 | error | Caught by controller[1]: at Object.assertActive (/opt/iobroker/node_modules/@matter/general/src/util/Lifecycle.ts:42:23)
host.HOMESERVER | 2024-12-01 19:52:56.447 | error | Caught by controller[1]: Error: 9d209b29-7f7d-4e3d-8350-c0bec0dbe945 is not initialized
host.HOMESERVER | 2024-12-01 19:52:56.446 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

</body>
</html>

adding a device from userdata, with the same object definition, it will work.

**Comment by Feuer-sturm** [comment]
@kesch001de Please make sure that in matter instance the option "Erweitertes Debug-Logging für das Matter-Protokoll aktivieren" is activated and that the log level of the matter instance is switched to "debug". This is needed to better analyze the issues.

**Comment by Apollon77** [comment]
Yes names will be shortened in next version

**Comment by Apollon77** [comment]
fixed in 0.2.4

**Comment by Apollon77** [comment]
also @tarikweiss
