### ISSUE TITLE
Popup "Hinweise zur Inbetriebnahme" - Begriff "Test vendor" nicht eindeutig

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.matter#192]
matter v0.2.3

Ich hab mir jetzt 2 VMs angelegt, in einer läuft der Matter Controller (VM-2) und in der anderen die Matter Brdiges / Geräte (VM-1). Ich habe gerade ein neues Gerät angelernt und über den QR Code Reader der VISU App das virtuelle Gerät mit dem Matter Controller verbunden. In der VM-2 wird mir nach erfolgreichem Pairing dieses Popup angezeigt.

![grafik](https://github.com/user-attachments/assets/de85ee54-316e-4a1a-98bb-79b011bdb354)

Bitte den Begriff "Test vendor" eindeutiger machen, dass es sich um ioBroker handelt (ggf. sogar mit ioBroker Logo), da wohl Openhab demnächst auch ein möglicher "Test vendor" sein kann (nach Rückmeldung von Apollon)

**Comment by Apollon77** [comment]
Lets do with combination 0xFFF1 + Vendor name === "ioBroker"

**Comment by GermanBluefox** [comment]
Front end implemented. vendorName must be provided in node info

**Comment by Apollon77** [comment]
Ok, i had an  error in thinking ... basically no way to know which controller is behind it ... But with next version we will show the fabric label ... So I added ... when fabric label 8as the default is used) contains "ioBroker" then we use this. If the user customizes the name and removes ioBroker then we have (again) no way

**Comment by Feuer-sturm** [comment]
matter 0.3.3
implemented :-)
![grafik](https://github.com/user-attachments/assets/0f929df6-f118-44f7-b834-0e7b1648a574)
