### ISSUE TITLE
Popup with alert if a device shall be deleted which is used in matter adapter

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.matter#194]
**Describe the bug**  
Last night I deleted a device from the ioBroker devices that was part of a matter bridge (in the Matter adapter (https://github.com/ioBroker/ioBroker.matter). This morning, of course, the Matter adapter complained loudly with error messages about the missing device. 

It should be recognize in ioBroker Device Adapter when an existing device in Matter is linked to a matter bridge / device, so that you get a corresponding message if you try to delete this device.

**Versions:**  
 - Adapter version: device v.1.1.5; matter.0 v0.2.3
 - JS-Controller version: 7.0.3

Edit 04.12.2024
Logfile
[message(2).txt](https://github.com/user-attachments/files/18005579/message.2.txt)

**Comment by Apollon77** [comment]
The original intent of the issue is not that easiely possible I think ... but the error handling in matter adapter is now more robust. please check which cases you still find

**Comment by Feuer-sturm** [comment]
matter 0.2.4
@Apollon77 

- added device HMIP Feuchtigkeit Sensor(alias.0.DevicesMatter.HMIP_Feuchtigkeit_Sensor) to bridge and connected bridge with google home app, value of humidity is visible -> ok
- Delete Device DevicesMatter.HMIP_Feuchtigkeit_Sensor in menu Devices of iobroker
- Manually Restart of matter.0 instance
- The following error messages is shown in the logfile 
-- Cannot initialize device 8035df4f-def5-4e2e-8cdf-2e9954cf19ca "HMIP Feuchtigkeit Sensor" because alias.0.DevicesMatter.HMIP_Feuchtigkeit_Sensor does not exist! Check configuration.

If this matches with your expectation we can close this issue


Full log of retest
[log1.txt](https://github.com/user-attachments/files/18022466/log1.txt)
