### ISSUE TITLE
Device-Management Progress is not displayed!

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.matter#199]
The adapter uses a progress DM method but this is not displayed.

Can be tested by replacing https://github.com/ioBroker/ioBroker.matter/blob/main/src/lib/DeviceManagement.ts#L287 with e.g. an Promise await timeout of 30s. ... and then in the UI klick on "delete " for a node

Backend requests are send and such but nothing is shown

There are also no errors in the browser console. and "Process received" or such is logged, so it received the progress command it seems

**Comment by Feuer-sturm** [comment]
matter 0.3.1

@Apollon77 während des Node löschen Vorgangs im iobroker Matter controller wird ein "in progress" Element in der UI angezeigt. Kann das issue damit geschlossen werden?
