### ISSUE TITLE
Add Welcome dialog to Adapter on first start

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.matter#208]
because Matter is special in some regards and also has some requirements I think it would be a cool idea to show a Welcome dialog to the user on first start in the UI.

And maybe we also could directly ask for the cloud credentials there?

Content could be:
* youneed IPv6
* UDP must flow
* Commissioning matter apps ideally use iot and te visu app
* enter cloud credentials

And then at the endof the page asking him what he wants to do  with 
* "Connect Matter devices with ioBroker" -> leads to Controller page
* "Expose iobroker devices as Matter bridge" -> leads to bridge page

I think this would be a good user onboading

**Comment by Feuer-sturm** [comment]
I would be great to guide the user for IPv6 and UDP and show him e.g. if ioBroker host has an IPv6 address or if UDP communication is possible (or give a hint)

**Comment by GermanBluefox** [comment]
<img width="686" alt="image" src="https://github.com/user-attachments/assets/d8e43c53-c46c-4730-81ee-f06c87732ef1" />

**Comment by Feuer-sturm** [comment]
@GermanBluefox @Apollon77 Is there any posibilty to give the user a hint how he can check if UDP is activated and working?

matter 0.3.2
welcome wizzard is implemented 🟢
