### ISSUE TITLE
controlelr schnell ein/aus kann fabric zerstören

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.matter#209]
Bug: controlelr schnell ein/aus kann fabric zerstören

Was wurde gemacht:
Ich hab vorhin den Merross Node gelöscht, dann ist die Verbindung von grün auf rot in der Kachel gewechselt und dann hab ich den Controller von ein auf aus geschaltet und jetzt geht er nicht man an.

Logfile
Siehe https://discord.com/channels/1071473433482891284/1310945036757893212/1314911582781702208

**Comment by Apollon77** [comment]
fixed in 0.2.7

**Comment by Feuer-sturm** [comment]
test ok with 0.3.0
während Löschvorgang kann matter controller nicht ausgeschaltet werden
