### ISSUE TITLE
Add Illuminance type and device

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.matter#212]

**Comment by Apollon77** [comment]
Done

**Comment by Feuer-sturm** [comment]
matter 0.3.2
Tested virtual "Dimmer" as a device which was connected with google home and had no problems.

**Comment by Apollon77** [comment]
(but dimer !== illuminance ...  :-) das wäre ein Brighness sensor

**Comment by Feuer-sturm** [comment]
:-)
Illuminane is also working
tested with matter 0.3.2
