### ISSUE TITLE
Pairing matter device with iob Matter controller using iob VISU App which shows at the end "Es ist ein Fehler aufgetreten"

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.matter#213]
matter 0.2.6 and 0.2.7
iot Adapter v3.4.3
VISU App v1.3.0 (Android)

Try to connect a matter device (Merross plug) with ioBroker Matter Controller
VISU App shows at the end of the commissioning "Es ist ein Fehler aufgetreten".
In iobroker matter controller the node and the device is shown in the matter controller tab and it is possible to switch the plug on/off

Log was sent to @Apollon77

**Comment by Apollon77** [comment]
@foxriver76 @GermanBluefox We need to check whats up here

**Comment by Apollon77** [comment]
Please try again. Before: Do in iot adapter a "neue verbindungszertifikate" and wait after restart till green again. Please then try again

**Comment by Feuer-sturm** [comment]
matter 0.3.2
visu app 1.3.1 and neue verbindungszertifikate selected

everything ok.
