### ISSUE TITLE
Show full IPv6 address in Netzwerkkonfiguration

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.matter#216]
Please show the full IPv6 address of the selected network interface
![grafik](https://github.com/user-attachments/assets/7656504f-6138-4734-a1e0-f3b44ed5d3b7)

**Comment by GermanBluefox** [comment]
Who does reading the IPv6 addresses? :)
What is your use-case?

**Comment by Feuer-sturm** [comment]
@GermanBluefox In the log file you will find only the ipv6 address and not the ipv4 address and it looked strange for me not to show the full ipv6 address.

**Comment by Feuer-sturm** [comment]
fixed with 0.2.9
