### ISSUE TITLE
Aqara U200 tile battery status is missing in the controller tab

### ISSUE THREAD

**Issue by d-berk** [ioBroker/ioBroker.matter#217]
After integrating the Aqara U200, the tile for the battery status for the U200 is no longer displayed (this was still possible with 0.2.4) and the following error occurs:

`warn: matter.0 (242) Error while executing command ‘controllerCommissionDevice’: Error: Property lowBattery not found`

Adapter version is 0.2.7
see also attached Log
[iobroker.2024-12-09.log](https://github.com/user-attachments/files/18074930/iobroker.2024-12-09.log)

![Screenshot 2024-12-09 224342](https://github.com/user-attachments/assets/f4103d4a-fd78-4699-a509-f7e5b601c7cf)

**Comment by Apollon77** [comment]
Should appear after restrt with update

**Comment by d-berk** [comment]
funktioniert wieder

**Comment by Joylancer** [comment]
bei mir auch
