### ISSUE TITLE
Add information to configuration "Standard-Bridge"

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.matter#219]
matter 0.2.7

current configuration option:
![grafik](https://github.com/user-attachments/assets/3e9ccbbd-d81b-4ebf-b84f-afef7121f8a3)

Please point out, that this configuration is only relevant for Alexa

- Seperate Headline "Konfiguration der Standard Bridge für Alexa"
- Add Dropdown under this headline
- Add/move this information (which is currently only in Tab Bridges" under the dropdown "Bitte beachten: Aufgrund von Einschränkungen des Amazon Alexa-Systems kann pro ioBroker-Host nur eine Bridge oder ein Gerät mit Alexa gekoppelt werden! Mit dieser Auswahl wird festgelegt, welche Bridge mit dem Alexa System gekoppelt werden kann. "

**Comment by GermanBluefox** [comment]
<img width="833" alt="image" src="https://github.com/user-attachments/assets/9fef6813-78fc-4366-93f3-482bca813722" />

**Comment by Feuer-sturm** [comment]
fixed with 0.2.9
