### ISSUE TITLE
Add information to configuration to controller tab "Geräte per Pairing-Code oder QR-Code hinzufügen"

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.matter#220]
matter 0.2.7

current screen:
![grafik](https://github.com/user-attachments/assets/52b50795-ce50-40b7-9d53-5086ac0a3b25)

Please add additional information for the popup
- Change Headline of the popup "Manuelles hinzufügen eines bereits verbundenen Matter Gerätes mit dem ioBroker Matter Controller"
- Add additional information in the pop up: "Vorbedingung: Das Matter Gerät muss bereits mit einem anderen Matter System verknüpft (z.B. Google, Apple, Alexa, ...) sein. Hier muss der QR-Code Kopplungscode eingegeben bzw. QR-Code gescannt werden, welche für dieses Matter Gerät in der App vom Matter Ökosystem (z.B. Google Home) bereitgestellt wird. Bitte NICHT den QR-Code / Kopplungscode verwenden, welcher auf dem Matter Gerät gedruckt ist."
- Think about changing the title of the button as well to "Manuelles hinzufügen eines bereits verbundenen Matter Gerätes mit dem ioBroker Matter Controller" or something similar.

**Comment by GermanBluefox** [comment]
<img width="353" alt="image" src="https://github.com/user-attachments/assets/29772b40-dc9e-400b-bd7c-ceebbd2b4b7b" />

**Comment by Feuer-sturm** [comment]
fixed in 0.3.1
