### ISSUE TITLE
Selection of matter adapter in Visu App on Android is empty

### ISSUE THREAD

**Issue by CommanderXXL** [ioBroker/ioBroker.matter#224]
I tried to to add matter devices via the Android app "Visu". But after selecting "Nein, das Gerät ist neu", the "Gerät hinzufügen" dialog is just empty. It shows an empty selection field when I try to set the drop-down for the "Matter-Instanz".
Otherwise the "Visu" app works fine for me.

Maybe this is a bug of the app and not of this adapter. Please move the ticket if this is the case.

**Comment by Apollon77** [comment]
Sanme issue I have ... we need to find the info

**Comment by Feuer-sturm** [comment]
This is how my settings looks like
Android
App version 1.3.0

![grafik](https://github.com/user-attachments/assets/d4548e89-fcfa-48e3-a765-95124fab2695)

I see a matter instanze.
When I started with visu app I did not see the matter instanz as well. I changed the ip address to the server where my active matter controller is running and I entered username and passwort for the server. After this  it worked.
(Of course there is a valid mail address for the pro account, I just only deleted it here for the screenshot)

**Comment by CommanderXXL** [comment]
I tried "Neue Verbindungszertifikate anfordern" and then restarted the iot adapter. Still not working. But I saw in the logs that the visu app is using the cloud connection, despite me being in local network. I got no password for my admin account, can this be the reason for the cloud fallback?

**Comment by Feuer-sturm** [comment]
@CommanderXXL which version of the visu app do you use? On Android version 1.3.1 is available.

**Comment by CommanderXXL** [comment]
@Feuer-sturm it is working now. The update came yesterday evening to my phone. Now "matter.0" is written in the instance field.
For some reason the connection always uses the cloud connection instead of the local one. But it is still working. I now try to add a new thread device to my OpenThread border router to check if everything works.

Thanks for your help.

**Comment by Feuer-sturm** [comment]
@CommanderXXL as far as I know from @Apollon77 it works as designed that the cloud connection is used for commisioning the new devies and not the local network
