### ISSUE TITLE
bridges/Devices Tab with many entries: Last one not deletable

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.matter#226]
because overlapping with the "+" button

<img width="1536" alt="Bildschirmfoto 2024-12-13 um 12 48 09" src="https://github.com/user-attachments/assets/ead22cc0-0b16-423f-ac26-09a56f8367b5" />

There should be al least one empty "line" as hight as the + button on the bottom

**Comment by Feuer-sturm** [comment]
matter 0.2.9
not fixed with current version
![grafik](https://github.com/user-attachments/assets/878f1c45-d74b-4e47-8781-ee7b833ac366)

**Comment by Feuer-sturm** [comment]
fixed with 0.2.10
symbol is now in the upper left corner :)
![grafik](https://github.com/user-attachments/assets/a818c26e-a570-4336-8639-a39700e88d9c)
