### ISSUE TITLE
[Feature request] Own tab similar to the Zigbee or Backup Adadpter

### ISSUE THREAD

**Issue by Xfrrbji** [ioBroker/ioBroker.matter#228]
Since you can pair and control devices with matter in a similar way to Zigbee, I would like to have a separate menu item comparable to Zigbee, Backup or Javascript for the administration of the device.

**Comment by GermanBluefox** [comment]
Done mit https://github.com/ioBroker/ioBroker.matter/pull/233

**Comment by Feuer-sturm** [comment]
@GermanBluefox How can this be tested? Where do I find the new menu?

**Comment by Apollon77** [comment]
@Feuer-sturm just at the right in the tabs like Adapter/instances and such. It is there for me

**Comment by Feuer-sturm** [comment]
is available :)
![grafik](https://github.com/user-attachments/assets/85933fe2-02d7-448e-badf-df360b4f5483)
