### ISSUE TITLE
Controller-Tab Pairing Dialog: Buttons ohne Funktion

### ISSUE THREAD

**Issue by d-berk** [ioBroker/ioBroker.matter#230]
wenn man den im controller pairen will, funktionieren die Buttons nicht, siehe screenshot. das Popup kann man auch nicht mehr schließen, nur adapter restart hilft. Log-Datei beginnt mit Adapter start und dann direkt auf pairing und danach versucht die buttons zu drücken...

Adapter Version: 0.2.8
JS-Controller: 7.0.3
Admin-Adapter: 7.1.5
![2024-12-17 220804](https://github.com/user-attachments/assets/20c7eb4e-dad1-44c8-a8b6-2b85f0b62e92)
[2024-12-17 Log - iot4db.txt](https://github.com/user-attachments/files/18171554/2024-12-17.Log.-.iot4db.txt)

**Comment by Apollon77** [comment]
Should be fixed in 0.2.9

**Comment by Feuer-sturm** [comment]
@d-berk did you had already the time to retest it with current version (today it is 0.3.2)?

**Comment by Apollon77** [comment]
should be fixed as also informed in discord.

**Comment by Feuer-sturm** [comment]
matter 0.3.3
Buttons are working in my matter controller.
