### ISSUE TITLE
Remove QR code an link for uncommissioned devices

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.matter#240]
matter 0.3.0

Please remove the qr code and the link  URL:  "https://project-chip.github.io/connectedhomeip/qrcode.html?data=" for uncommissioned  devices in ioBrokoer log
The QR code in the log file can not be scanned with a camera.

**Comment by Apollon77** [comment]
is removed in next update

**Comment by Feuer-sturm** [comment]
fixed with matter 0.3.3
