### ISSUE TITLE
Adapter already working?

### ISSUE THREAD

**Issue by TobiKr** [ioBroker/ioBroker.matter#3]
I installed this adapter and was able to create an instance. Is this already supposed to work? I am not able to see any device and noticed a "disconnected icon" in the upper right corner
<img width="1474" alt="image" src="https://github.com/ioBroker/ioBroker.matter/assets/9446386/00be43bf-8277-4a78-b1a4-90b313bba5b6">

**Comment by GermanBluefox** [comment]
It is working, but only as device or bridge (ioBroker can simulates matter devices). What you expect is a controller mode and I am just now working on it.

**Comment by TobiKr** [comment]
Thank you! I am looking for a way to get sensor readings/status from devices already connected to Apple Home via matter - is this possible at all?
