### ISSUE TITLE
How do we have the user define one devcie as "default for port 5540" (aka Alexa discoverable)?

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.matter#40]
We need a way to declare one device or bridge as "the one that gets port 5540 and its the only one on this host that is Alexa discoverable (as of now). And ideally also check this to let the user re-assign that flag if such a bridge got deleted or such.

Also: How to do this on UI level?

**Comment by foxriver76** [comment]
So will it have a prop in `native` to detect it or how do you need it in backend?

**Comment by Apollon77** [comment]
We can have a property like "defaultBridge" or "port:5540" :-) and backend can use it to make sure it is sorted and processed firstto get the wanted port number If not existing then the backend could print a warning and assign by random

**Comment by foxriver76** [comment]
I mean default bridge would be more user friendly but if it would be useful to configure port per bridge, we can also go with a approach having a number input and a button to make the bridge default which then sets port to 5540

**Comment by Apollon77** [comment]
Ok, to summarize in my eyes:

Issue is: We can only publish ONE device or bridge on Port 5540 which is the Matter default port - and the only one discovered by Alexa currently! So we can have multiple devices and bridges per host, but only ONE that works with Alexa. Lets call that "(Alexa Compatible) Default Device".

How the user can now define what's this default device?

* Option A is a property in the device/bridge settings  about a default-flag or the port assignment ... this requires always a check in all other devices and bridges to make sure it is not applied twice. And when the default thing gets deleted via UI or objects) we need to somehow remind. the user to choose. a new default, or we have none and port 5540 is assigned by random to the first entry in the array. (PS: Allowing to assign ports by users is also a meeh thing because we can hide that complexity for him)
* Option B is to have a "global" property which contains the "default/alexa-compatible device/bridge" and choose the UUID of the device/bridge there in one place ... this requires a validity check if the ID is still existing and also handling on deletion and initialization and a warning that the user can reassign it.

For me it feels that Option B is more clear and we could really name it "Alexa Compatible bridge/Device". We could also store this in the adapter settings because changing this most likely means port reassignments, so a full restart is not the worst idea

**Comment by foxriver76** [comment]
is this done on backend side too? @Apollon77

**Comment by Apollon77** [comment]
Yes it's done. can be closed
