### ISSUE TITLE
sync login infos with iot adapter not work

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.matter#56]
![grafik](https://github.com/user-attachments/assets/f2972589-e3d9-4853-bdf2-ccc09b8f23a0)

**Comment by foxriver76** [comment]
For me it fills password on first click and on another click it fills username. Is it the same for you or completely not working?

**Comment by foxriver76** [comment]
but tbh the UI from your screenshot looks a bit outdated
